### PR TITLE
Allow static builds with Meson

### PR DESCRIPTION
**Pull request by ximion**
This PR adds a Meson build definition to DerelictPQ. I use this via ddbc and hibernated in a project for a while now, and the Meson definition works well.

Since Meson will likely be mostly used in the context of adding this module to Linux distributions, the Meson build definition only compiles the static version, and has no option for building the dynamically loaded DerelictPQ version (which would be a bit more complicated due to the dependency on Derelict).

Additionally to the Meson patch, this PR also fixes a bug regarding building with `Derelict_Static`.
I hope you find this useful!

(I found no CI for DerelictPQ, if there is one, I could add a test for this as well)

### CODE REVIEW

**Comment by mdparker** [comment]
Thanks for the PR! 

Regarding Meson, I'm sorry to say I have no interest in adding support to any of the DerelictOrg packages for any build systems other than DUB. If I add Meson into one, someone else will want it in another. Then why not add support for CMake? Or add Visual Studio Projects? Then the maintenance burden for all of that falls on my shoulders. Not going down that road :-)

As for the static bug, the proper fix is to make it match the version block in pq.d:

```d
version(Derelict_Static) version = DerelictPQ_Static;
version(DerelictPQ_Static):
```

That's now fixed in both 3.0.0-beta.4 and 4.0.0-alpha.2. Thanks!

**Comment by denizzzka** [comment]
> Regarding Meson, I'm sorry to say I have no interest in adding support to any of the DerelictOrg packages for any build systems other than DUB. If I add Meson into one, someone else will want it in another. Then why not add support for CMake? Or add Visual Studio Projects?

What if add it throughout derelict-util?

**Comment by denizzzka** [comment]
Also, Ludwig made dynamic bindings generator. You seen it?
"Generates dynamic bindings from static bindings at compile time"
http://code.dlang.org/packages/dynamic

**Comment by mdparker** [comment]
> What if add it throughout derelict-util?

To what end?

> Also, Ludwig made dynamic bindings generator. You seen it?

Not before now. But from what I can see, it simply converts static binding declarations to dynamic form. I already have a custom script I use to covert derelict-specific function pointer alias declarations to static declarations.

At any rate, all of this will become moot in the near future. I'll soon be making an announcement about the future of Derelict -- it's going into maintenance-only mode. I've gone back to the drawing board and come up with something much simpler that a) addresses a number of maintenance issues I'm having with the Derelict packages, b) is @nogc, nothrow, betterC compatible, and c) is more configurable at compile-time.

**Comment by ximion** [comment]
@mdparker In that case I will have to maintain a permanent fork of this project.
I need it as part of the DerelictPQ -> ddbc -> hibernated -> laniakea dependency chain (the last one I want in Debian, the middle two still need a few patches upstreamed).
Dub doesn't work that well for complex projects (involving configuring lots of files, adding C code, ...) and doesn't work at all for packaging software in Linux distributions such as Debian and Fedora (there are issues filed for those problems though). Using a dub-using project from other build systems is at the moment impossible as well (but becomes possible via Meson due to it generating a general-purpose pkg-config file).
In any case, thanks for considering!

**Comment by mdparker** [comment]
@ximion Would you like to take over as maintainer of DerelictPQ? I will happily add you to the organization. That's why it's here. Then you can add Meson if you want and I don't have to worry about it :-)

**Pull request closed without merging**
